### ISSUE TITLE
Use ansible-galaxy to get the elasticsearch role

### ISSUE THREAD

**Issue by elmendalerenda** [coopdevs/timeoverflow-provisioning#6]
The elasticsearch role is fetched currently as a git submodule, which force to execute an extra command during the provisioning. Migrating to ansible-galaxy will make this step more automatic and less confusing.

**Comment by enricostano** [comment]
One thing that we need to check is how to deal with the production environment since it is slightly different right now. IIRC we have elasticsearch installed with a custom role made by us.

We need to check that we don't break anything provisiong production.

It's important IMO that our production and development environments are as similar as possible.

But yes, it seems a good idea to use the `ansible-galaxy` roles and adding the `vendor` directory to `.gitignore`.
